SELECT USER_ID , NICKNAME , sum(price) as TOTAL_SALES  from USED_GOODS_BOARD
join USED_GOODS_USER on USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID 
where STATUS = "DONE"
group by USER_ID 
having  TOTAL_SALES >= 700000 
order by TOTAL_SALES ;