select B.TITLE , R.BOARD_Id , R.REPLY_ID , R.WRITER_ID , R.CONTENTS , DATE_FORMAT(R.CREATED_DATE , "%Y-%m-%d") as CREATED_DATE from USED_GOODS_BOARD B inner join USED_GOODS_REPLY R on B.BOARD_Id = R.BOARD_Id where B.CREATED_DATE like "2022-10%" ORDER BY
R.CREATED_DATE	, B.TITLE ;
